spring:
  kafka:
    topics:
      prescriptions: ${PRESCRIPTION_TOPIC}
      patient-profiles: ${PATIENT_PROFILE_TOPIC}
      dispensation-acks: ${DISPENSATION_ACK_TOPIC}
    dlq:
      topic: ${DLQ_TOPIC:scpro-elmis-dlq}
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config:  ${JAAS_CONFIG}
  application:
    name: zm-scpro-elmis-pipeline